app = "vyx-user-35682909"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  USER_ID = "63eea370-27a1-4099-866a-e3ed340b278d"
  RUN_MODE = "user_dedicated"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
  cpus = 2
